@Catalog.API_HostAddress = http://localhost:5000

POST {{Catalog.API_HostAddress}}/api/products
Content-Type: application/json

{
    "Name":"Product 1",
    "Description":"Add new products",
    "ImagePath":"image path",
    "Price":20
}

###


GET {{Catalog.API_HostAddress}}/api/products

###

POST {{Catalog.API_HostAddress}}/api/categories
Content-Type: application/json

{
  "Name":"Milk",
  "Description":"Choose between many fresh products",
   "ImagePath":"http:///"
}

###

GET {{Catalog.API_HostAddress}}/api/categories/123e4567-e89b-12d3-a456-426614174000

###
